---
- hosts: all
  vars:
     page_output: Jason's awesome page

  tasks:
  - name: install podman
    package:
      name: "podman"
      state: present
      
  - name: Ensure httpd image is present
    containers.podman.podman_image:
      name: docker.io/library/httpd
      tag: latest
      state: present

  - name: Index.html file is present
    copy:
      src: /root/ws1/index.html
      dest: /home
      remote_src: yes
  
  - name: SELinux policy for httpd is enabled
    community.general.sefcontext:
      target: '/home(/.*)?'
      setype: container_file_t
      state: present
    register: selinux

  - name: SELinux context are enabled
    ansible.builtin.command: restorecon -irv /home
    when: selinux.changed
    
  - name: httpd is running
    containers.podman.podman_container:
      name: jason-httpd
      image: httpd
      state: started
      detach: true
      exposed_ports:
        - 80
      ports:
        - 4444:80
      volumes: /home/:/usr/local/apache2/htdocs/
    
  - name: Test httpd response is correct
    uri:
      url: http://localhost:4444
      return_content: yes
    register: this
    failed_when: " {{ page_output }} not in this.content"