---
- hosts: all
  tasks:
  - name: installing podman
    package:
      name: "podman"
      state: present
  - name: Pull an image
    containers.podman.podman_image:
      name: docker.io/library/httpd
  - name: Copying file into home
    copy:
      src: /root/ws1/index.html
      dest: /home
      remote_src: yes
  - name: Re-create a httpd container
    containers.podman.podman_container:
      name: jason-httpd
      image: httpd
      state: started
      detach: true
      exposed_ports:
        - 80
      ports:
        - 4444:80
      volumes: /home/:/usr/local/apache2/htdocs/